name: workflow1
on:
  pull_request:
    branches:
      - main
  push:
    branches: 
      - main
  # schedule:
  #   - cron:  '*/5 * * * *'
  workflow_dispatch:
    inputs:
      my_input:
        description: 'sample example'
        required: true
        default: 'abc'
        type: string
jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      MY_VAR: my_value
    steps:
      - name: step1
        run: echo "Hello"
      - name: step2
        run: |
          echo $MY_VAR
          echo "My input is: ${{ github.event.inputs.my_input }}"
      - run: echo "hello from step 3, without name"
  job2:
    runs-on: ubuntu-latest
    env:
      MY_VAR: my_value2
    steps:
      - name: step1
        run: echo "Hello2"
      - name: step2
        run: |
          echo $MY_VAR
          echo "My input is: ${{ github.event.inputs.my_input }}"
