name: workflow2
on:
  push:
    branches: 
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Hello"
      - name: step2
        run: |
          echo "ABC"
          echo "123"
 
